services:
  - type: web
    name: fyers-proxy-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FYERS_CLIENT_ID
        sync: false
      - key: FYERS_SECRET_KEY
        sync: false
      - key: FYERS_REDIRECT_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
